using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using Rotativa.AspNetCore;
using System.IO;

namespace SarExportSuite.Controllers
{
    public class ExportController : Controller
    {
        // sar: Main page for export options
        public IActionResult Index()
        {
            return View();
        }

        // sar: Export Excel file with dummy data
        public IActionResult ExportExcel()
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            using var package = new ExcelPackage();
            var sheet = package.Workbook.Worksheets.Add("sar-sheet");

            // Headers
            sheet.Cells[1, 1].Value = "Nama";
            sheet.Cells[1, 2].Value = "Pekerjaan";
            sheet.Cells[1, 3].Value = "Email";

            // Data Rows
            sheet.Cells[2, 1].Value = "Sarah Hart";
            sheet.Cells[2, 2].Value = "Junior .NET Developer";
            sheet.Cells[2, 3].Value = "sar@sar.dev";

            sheet.Cells[3, 1].Value = "Dewi A.";
            sheet.Cells[3, 2].Value = "UI Designer";
            sheet.Cells[3, 3].Value = "dewi@sar.dev";

            // Footer watermark
            sheet.Cells[5, 1].Value = "Generated by SarExportSuite";

            var stream = new MemoryStream();
            package.SaveAs(stream);
            stream.Position = 0;

            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "sar-data.xlsx");
        }

        // sar: Export PDF from Razor view
        public IActionResult ExportPdf()
        {
            var model = new
            {
                Title = "Laporan Pengguna",
                Users = new[]
                {
                    new { Nama = "Sarah Hart", Pekerjaan = "Developer" },
                    new { Nama = "Dewi A.", Pekerjaan = "Designer" }
                }
            };

            return new ViewAsPdf("PdfView", model)
            {
                FileName = "sar-laporan.pdf",
                CustomSwitches = "--footer-center \"Generated by sar\" --footer-line"
            };
        }
    }
}
